# Generated by Django 5.2.4 on 2025-08-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('productos', models.ManyToManyField(related_name='pedidos', to='productos.producto')),
            ],
        ),
    ]
