# Generated by Django 5.2.4 on 2025-08-05 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('fecha_entrega', models.DateField()),
                ('codigo_rastreo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='etiquetas/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='pedidos.pedido')),
            ],
        ),
    ]
